[package]
name = "rusty_todo"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
serde = { version = "1.0.219", features = ["serde_derive"] }
serde_json = "1.0.142"
